apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camel-ai-qdrant
  namespace: camel-ai
spec:
  destination:
    namespace: camel-ai
    server: https://kubernetes.default.svc
  project: default
  source:
    path: etc/kubernetes/base/qdrant
    repoURL: https://github.com/lburgazzoli/camel-ai
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ServerSideApply=true